image: archlinux
packages:
  - go
  - postgresql
sources:
  - https://github.com/go-ap/jsonld
environment:
  GO111MODULE: 'on'
tasks:
  - setup: |
      cd jsonld && go mod download
  - tests: |
      cd jsonld && make test
  - coverage: |
      set -a +x
      cd jsonld && make coverage
      GIT_SHA=$(git rev-parse --verify HEAD)
      GIT_BRANCH=$(git name-rev --name-only HEAD)
