image: archlinux
secrets:
- da1f93b4-c155-406b-9efd-75d9c8d41454f
packages:
  - go
  - postgresql
sources:
  - https://github.com/go-ap/jsonld
environment:
  GO111MODULE: 'on'
tasks:
  - setup: |
      cd jsonld && go mod download
  - tests: |
      cd jsonld && make test
  - coverage: |
      set -a +x
      cd jsonld && make coverage
      GIT_SHA=$(git rev-parse --verify HEAD)
      GIT_BRANCH=$(git name-rev --name-only HEAD)
      source ~/.code-cov.sh
      curl -X POST \
          --data-binary @jsonld.coverprofile \
          -H 'Accept: application/json' \
          "https://codecov.io/upload/v2?commit=${GIT_SHA}&token=${JSONLD_TOKEN}&branch=${GIT_BRANCH}&service=custom"
