language: go

go:
- '1.10'
- '1.11'
- 'tip'

env:
  secure: "B7PKS+9jFFJ4puyReHouWyKHqUrGMiBkSmpVWzM4E1gOMwzQmzY7achtba/BVmE8V5rzjj9OnqmiIJQCuDSTuguL5bH8cCk3n9M+KHBVCwSF2vJYRKMhcClmjmzQJpLpy/Gsp3PtaosMaPc3WKlYx/N76hjqg/gq2CrJU+dfIsiYUSV2CKUVXuqOLO4Sh+84nMBGFbR0aWRUGYdRr0qRlCbg+0l5l/nyHy4wluQt1LAm7SRZYqZJLnWoE1oIMG5D4rPzTtqT2hKpCHbxYIUmtY7kNLulikLdseIDF0ii1SdHRjGAQOS++FwMX0i5fqSTXNvmyVSenTJh+g3aVf5prJOjS+5GKd/rYoSHNf+zWPCiehyeE2klY7mEXQJEWnSHtIzQ7G7TrxSTl4z99TvzcvXM+vDG1b829TbGERaUqkr2p+nW2IEV6rJQO2o8SyWqB/QwisY6ombVcR33zOzFkHozLW1yjed+VdRF/N647MC2r5hKMn/dx0nP2x6ihRO9AJnqqd1KFd1p9SWJ+hzGiwO/P5iTRgdhXsR3YfrEvM315fadM2997aQZ53FabD+NgMY41MHGggLoDI3XcrW8Rs90hG3mx3eI1OK+XXi0vYl7Mw887zdgZ3n+KGqNhcXWmwnB1PV17hCQXV2gJkKi1gacclxErO3svFddY76mj1Y="
matrix:
  allow_failures:
  - go: tip
  fast_finish: true

install:
- go get -t -v ./...

script:
- go test -v ./...

after_success:
- go test -cover -coverprofile jsonld.coverprofile ./...
- bash <(curl -s https://codecov.io/bash) -f jsonld.coverprofile
